# Configuration for Crypto News Monitor

# BlockBeats API base URL
api_base_url: 'https://api.theblockbeats.news'

# API endpoint for flash news (no API key required)
api_endpoint: '/v2/rss/newsflash'

# API key for BlockBeats (leave empty if no key required)
api_key: ''

# Keywords to monitor in news articles - specifically for BTC, ETH, SOL, DOT, WIF
news_keywords: 
  - 'bitcoin'
  - 'BTC'
  - 'btc'
  - 'ethereum'
  - 'ETH'
  - 'eth'
  - 'solana'
  - 'SOL'
  - 'sol'
  - 'polkadot'
  - 'DOT'
  - 'dot'
  - 'wif'
  - 'WIF'
  - 'dogwifhat'
  - 'crypto'
  - 'cryptocurrency'
  - 'token'

# How often to check for news (in seconds)
refresh_rate: 120  # 2 minutes - more frequent for flash news

# Directory for storing data
data_dir: 'data/'

# Maximum number of articles to fetch per cycle
max_articles_per_cycle: 20

# Notification methods to use ('console', 'file', 'telegram')
notification_methods: ['console', 'file', 'telegram']

# Telegram settings (if using Telegram notifications)
telegram_bot_token: ''
telegram_chat_id: ''